import type { Metadata } from "next"
import "./globals.css"
import { lexend } from "../../styles/fonts"
import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          lexend.className
        )}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  )
}
