import type { Metadata } from "next"
import "./globals.css"
import { lexend } from "../../styles/fonts"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-provider"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased flex flex-col",
          lexend.className
        )}
      >
        <ThemeProvider>
          <div className="flex-1">
            {children}
          </div>
          
        </ThemeProvider>
      </body>
    </html>
  )
}
